Add support for Scroll pHAT HD from Pimoroni
adafruit/Adafruit_CircuitPython_IS31FL3731 pull request #23
Opened 2020-03-14 23:06 UTC by dglaude

Tested on CLUE using BIT:2:Pi to plug the Scroll pHAT HD.
Used the same orientation as the CharliePlex LED matrix Bonnet.
Added this option in all example, and enabled it on the Adafruit Scroll Text example.

PS: Should also work for the new Scroll HAT Mini.

2020-03-14 23:52 UTC, dglaude commented
Demo of the code in action: https://twitter.com/DavidGlaude/status/1238974062560411649?s=20

2020-03-15 03:38 UTC, ladyada requested changes

2020-03-15 03:38 UTC, ladyada commented on adafruit_is31fl3731.py
> +__version__ = "2.5.3"
revert this

2020-03-15 03:38 UTC, ladyada commented on examples/is31fl3731_text_example.py
> +display = adafruit_is31fl3731.ScrollPhatHD(i2c)
revert, dont make scrollphat the default

2020-03-15 07:11 UTC, dglaude commented
Requested change done.

2020-03-15 15:15 UTC, ladyada approved these changes

2020-03-15 15:15 UTC, merged

2020-03-15 15:15 UTC, ladyada commented
ok thanks!